<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<LangVersion>Latest</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<!-- Debug is useless for a mod -->
		<DebugType>none</DebugType>
		<Platforms>AnyCPU;x64</Platforms>
	</PropertyGroup>

	<PropertyGroup>
		<TheLongDarkPath>D:\SteamLibrary\steamapps\common\TheLongDark</TheLongDarkPath>
	</PropertyGroup>

	<ItemGroup>
	  <None Remove="Localization.json" />
	  <None Remove="Resources\Icons\Alt\AcclimatizedII_ALT.png" />
	  <None Remove="Resources\Icons\Alt\AcclimatizedI_ALT.png" />
	  <None Remove="Resources\Icons\Alt\AMSrisk_ALT.png" />
	  <None Remove="Resources\Icons\Alt\AMS_ALT.png" />
	  <None Remove="Resources\Icons\AMS.png" />
	  <None Remove="Resources\Icons\AMSrisk.png" />
	  <None Remove="Resources\Icons\Aperture.png" />
	  <None Remove="Resources\Icons\Classic\AcclimatizedI.png" />
	  <None Remove="Resources\Icons\Classic\AcclimatizedII.png" />
	  <None Remove="Resources\Icons\Classic\AMS.png" />
	  <None Remove="Resources\Icons\Classic\AMSrisk.png" />
	</ItemGroup>	
	
	<!-- List of used references -->
	<ItemGroup>		<!-- This is only if you use the ModSettings -->
		<!-- Only if you need ModData  -->
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
		<PackageReference Include="Waltz.Modding.TLD.Il2CppAssemblies.Windows" Version="2.52.0" />
	</ItemGroup>

	<!-- Most commonly used using's. Add to this so you dont need to define them in the cs files -->
	<ItemGroup>
		<Using Include="System.Reflection" />
		<Using Include="System.Diagnostics.CodeAnalysis" />
		<Using Include="Il2Cpp" />
		<Using Include="HarmonyLib" />
		<Using Include="MelonLoader" />
		<Using Include="UnityEngine" />
		<!-- Only if your using ModSettings -->
		<Using Include="ModSettings" />
		<!-- Only if your using ModComponent -->
		<Using Include="ModComponent" />
	</ItemGroup>

	<PropertyGroup>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
		<EnableDefaultCompileItems>false</EnableDefaultCompileItems>
	</PropertyGroup>

	<ItemGroup>
		<Compile Include="AfflictionSaveHelper.cs" />
		<Compile Include="Afflictions\CriticalAcclimatized.cs" />
		<Compile Include="Afflictions\AMS.cs" />
		<Compile Include="Afflictions\AMSrisk.cs" />
		<Compile Include="Afflictions\InsufficientAcclimatized.cs" />
		<Compile Include="Core.cs" />
		<Compile Include="OxModSettings.cs" />
		<Compile Include="Patches\VisualPatch.cs" />
		<Compile Include="Persistence\OLState.cs" />
		<Compile Include="Persistence\SaveDataManager.cs" />
		<Compile Include="Resources\Localization\ILocalizableAffliction.cs" />
		<Compile Include="Resources\Localization\LocalizationRefresh.cs" />
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Include="Resources\Icons\Alt\AcclimatizedII_ALT.png" />
	  <EmbeddedResource Include="Resources\Icons\Alt\AcclimatizedI_ALT.png" />
	  <EmbeddedResource Include="Resources\Icons\Alt\AMSrisk_ALT.png" />
	  <EmbeddedResource Include="Resources\Icons\Alt\AMS_ALT.png" />
	  <EmbeddedResource Include="Resources\Icons\Classic\AcclimatizedI.png" />
	  <EmbeddedResource Include="Resources\Icons\Classic\AcclimatizedII.png" />
	  <EmbeddedResource Include="Resources\Icons\Classic\AMS.png" />
	  <EmbeddedResource Include="Resources\Icons\Classic\AMSrisk.png" />
	  <EmbeddedResource Include="Resources\Localization\Localization.json" />
	</ItemGroup>

	<ItemGroup>
	  <Reference Include="ModComponent">
	    <HintPath>$(TheLongDarkPath)\Mods\ModComponent.dll</HintPath>
	  </Reference>
	  <Reference Include="AfflictionComponent">
		<HintPath>$(TheLongDarkPath)\Mods\AfflictionComponent.dll</HintPath>
	  </Reference>
		<Reference Include="ModSettings">
			<HintPath>$(TheLongDarkPath)\Mods\ModSettings.dll</HintPath>
		</Reference>
		<Reference Include="ModData">
			<HintPath>$(TheLongDarkPath)\Mods\ModData.dll</HintPath>
		</Reference>
	</ItemGroup>

	<!-- This is a build event. It will copy your dll to the currently defined TheLongDarkPath's Mods folder -->
	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<!-- This copies the mods files to the games mod dir -->
		<Copy SourceFiles="$(TargetPath)" DestinationFolder="$(TheLongDarkPath)/Mods" />
	</Target>
</Project>